site_name: TAP - Spring Boot with Postgresql
site_url: https://joostvdg.github.io/spring-boot-posgres/
site_description: Demo project for Spring Boot with Postgresql &amp; Service Bindings
docs_dir: docs/
repo_name: joostvdg/spring-boot-posgres
repo_url: https://github.com/joostvdg/spring-boot-posgres
edit_uri: ''
copyright: 'Copyright &copy; 2023 Joost van der Griendt'

# Theme
# Configuration
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.annotate
  name: material
  language: 'en'
  icon:
    logo: material/cloud
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

plugins:
  - techdocs-core
  - tags
  - git-revision-date-localized:
      type: iso_datetime
  - search
  - minify:
      minify_html: true

extra:
  generator: false
  version:
    method: mike
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joostvdg
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joost_vdg
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/joostvdg

# Extensions
markdown_extensions:
  - abbr
  - footnotes
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
- HOME: index.md
