apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres
  labels:
    app.kubernetes.io/name: spring-boot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot-postgres
    spec:
      containers:
        - name: spring-boot-postgres
          image: joostvdgtanzu/spring-boot-postgres-01:0.1.0
          env:
            - name: SERVICE_BINDING_ROOT
              value: "/bindings"
          ports:
            - containerPort: 8080
              name: http-web-svc
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /bindings/db
              name: secret-volume
              readOnly: true
      volumes:
        - name: secret-volume
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: postgresql-0001